'use client'
import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react'
import { createDefaultData, defaultProfile, makeDefaultItems } from '@/data/defaults'
import { generateCategories, generateChecklist } from '@/lib/checklistGenerator'
import { storageKey } from '@/lib/constants'
import { AppData, Category, ChecklistItem, Luggage, UserProfile } from '@/types/checklist'

type LegacyProfile=Partial<UserProfile>&{studentType?:'undergraduate_new'|'postgraduate_new'|'returning'|'other'}
type Store={data:AppData;ready:boolean;saveProfile:(p:UserProfile)=>void;updateItem:(item:ChecklistItem)=>void;addItem:(item:ChecklistItem)=>void;removeItem:(id:string)=>void;updateCategory:(c:Category)=>void;addCategory:(c:Category)=>void;removeCategory:(id:string)=>void;addLuggage:(l:Luggage)=>void;removeLuggage:(id:string)=>void;reset:()=>void;clear:()=>void;replace:(d:AppData)=>void}
const Context=createContext<Store|null>(null)
function migrateProfile(source:LegacyProfile):UserProfile{if(source.studentStatus)return {...defaultProfile,...source,educationStage:source.studentStatus==='new'?(source.educationStage||'undergraduate'):undefined,militaryTraining:source.studentStatus==='new'?(source.militaryTraining||'unknown'):'no'};if(source.studentType==='postgraduate_new')return {...defaultProfile,...source,studentStatus:'new',educationStage:'postgraduate'};if(source.studentType==='returning')return {...defaultProfile,...source,studentStatus:'returning',educationStage:undefined,militaryTraining:'no'};if(source.studentType==='other')return {...defaultProfile,...source,studentStatus:'new',educationStage:'undergraduate',needsIdentityConfirmation:true};return {...defaultProfile,...source,studentStatus:'new',educationStage:'undergraduate'}}
function migrateData(saved:AppData){const profile=migrateProfile(saved.profile as LegacyProfile);const defaults=makeDefaultItems();const normalized=(saved.items||[]).map(item=>{const system=defaults.find(x=>x.id===item.id||(x.name===item.name&&x.categoryId===item.categoryId));if(!system)return {...item,itemType:item.itemType||'physical'};return {...system,...item,itemType:system.itemType,helperText:system.helperText,priority:system.priority,status:item.itemType?item.status:system.status}});const items=generateChecklist(profile,normalized);return {...saved,version:5,profile,items,categories:generateCategories(profile,items,saved.categories||[])} as AppData}
export function ChecklistProvider({children}:{children:ReactNode}){const [data,setData]=useState<AppData>(createDefaultData);const [ready,setReady]=useState(false);useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw)setData(migrateData(JSON.parse(raw) as AppData))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify(data))},[data,ready]);const value=useMemo<Store>(()=>({data,ready,saveProfile:p=>setData(d=>{const profile={...p,needsIdentityConfirmation:false,educationStage:p.studentStatus==='new'?(p.educationStage||'undergraduate'):undefined,militaryTraining:p.studentStatus==='new'?(p.militaryTraining||'unknown'):'no'};const items=generateChecklist(profile,d.items);return {...d,version:5,profile,onboarded:true,items,categories:generateCategories(profile,items,d.categories)}}),updateItem:item=>setData(d=>({...d,items:d.items.map(x=>x.id===item.id?item:x)})),addItem:item=>setData(d=>({...d,items:[item,...d.items]})),removeItem:id=>setData(d=>({...d,items:d.items.filter(x=>x.id!==id)})),updateCategory:c=>setData(d=>({...d,categories:d.categories.map(x=>x.id===c.id?c:x)})),addCategory:c=>setData(d=>({...d,categories:[...d.categories,c]})),removeCategory:id=>setData(d=>({...d,categories:d.categories.filter(x=>x.id!==id),items:d.items.filter(x=>x.categoryId!==id)})),addLuggage:l=>setData(d=>({...d,luggage:[...d.luggage,l]})),removeLuggage:id=>setData(d=>({...d,luggage:d.luggage.filter(x=>x.id!==id),items:d.items.map(x=>x.luggageId===id?{...x,luggageId:undefined}:x)})),reset:()=>setData(d=>{const base=createDefaultData();const items=generateChecklist(d.profile);return {...base,version:5,onboarded:true,profile:d.profile,items,categories:generateCategories(d.profile,items)}}),clear:()=>setData(createDefaultData()),replace:d=>setData(migrateData(d))}),[data,ready]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useChecklist=()=>{const value=useContext(Context);if(!value)throw new Error('Provider missing');return value}

