'use client'
import { createContext,ReactNode,useContext,useEffect,useMemo,useState } from 'react'
import { createDefaultData } from '@/data/defaults'
import { generateCategories,generateChecklist } from '@/lib/checklistGenerator'
import { storageKey,DATA_VERSION } from '@/lib/constants'
import { migrateData } from '@/lib/dataMigration'
import { applyBatchItemPatch,BatchItemPatch } from '@/lib/batchItems'
import { AppData,Category,ChecklistItem,Luggage,UserProfile } from '@/types/checklist'
type Store={data:AppData;ready:boolean;saveProfile:(p:UserProfile)=>void;updateItem:(i:ChecklistItem)=>void;addItem:(i:ChecklistItem)=>void;removeItem:(id:string)=>void;updateCategory:(c:Category)=>void;addCategory:(c:Category)=>void;removeCategory:(id:string)=>void;addLuggage:(l:Luggage)=>void;removeLuggage:(id:string)=>void;batchMarkPrepared:(ids:string[])=>void;batchUpdateItems:(ids:string[],patch:BatchItemPatch)=>void;batchRemoveItems:(ids:string[])=>void;batchCategories:(ids:string[],action:'show'|'hide')=>void;batchRemoveCategories:(ids:string[],itemAction:'move'|'delete')=>void;reset:()=>void;clear:()=>void;replace:(d:unknown)=>void}
const Context=createContext<Store|null>(null)
export function ChecklistProvider({children}:{children:ReactNode}){
 const [data,setData]=useState<AppData>(createDefaultData);const [ready,setReady]=useState(false)
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw)setData(migrateData(JSON.parse(raw)))}catch{}setReady(true)},[])
 useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify(data))},[data,ready])
 const value=useMemo<Store>(()=>({data,ready,
 saveProfile:p=>setData(d=>{const profile={...p,needsIdentityConfirmation:false,educationStage:p.studentStatus==='new'?(p.educationStage||'undergraduate'):undefined,militaryTraining:p.studentStatus==='new'?(p.militaryTraining||'unknown'):'no'};const forced=d.categories.filter(c=>c.visibilityOverride==='show').map(c=>c.id);const items=generateChecklist(profile,d.items,forced);return {...d,version:DATA_VERSION,profile,onboarded:true,items,categories:generateCategories(profile,items,d.categories)}}),
 updateItem:item=>setData(d=>({...d,items:d.items.map(x=>x.id===item.id?item:x)})),addItem:item=>setData(d=>({...d,items:[item,...d.items]})),removeItem:id=>setData(d=>({...d,items:d.items.map(x=>x.id===id&&x.isSystemItem?{...x,hidden:true,visibilityOverride:'hide' as const}:x).filter(x=>x.id!==id||x.isSystemItem)})),
 updateCategory:c=>setData(d=>{const override=c.hidden?'hide' as const:'show' as const;const forced=c.hidden?[]:[...d.categories.filter(x=>x.visibilityOverride==='show').map(x=>x.id),c.id];const baseItems=d.items.map(x=>x.categoryId===c.id&&x.visibilityOverride!=='hide'?{...x,hidden:c.hidden}:x);const items=c.hidden?baseItems:generateChecklist(d.profile,baseItems,forced);return {...d,categories:d.categories.map(x=>x.id===c.id?{...c,visibilityOverride:override}:x),items}}),
 addCategory:c=>setData(d=>({...d,categories:[...d.categories,c]})),removeCategory:id=>setData(d=>({...d,categories:d.categories.filter(x=>x.id!==id),items:d.items.filter(x=>x.categoryId!==id)})),addLuggage:l=>setData(d=>({...d,luggage:[...d.luggage,l]})),removeLuggage:id=>setData(d=>({...d,luggage:d.luggage.filter(x=>x.id!==id),items:d.items.map(x=>x.luggageId===id?{...x,luggageId:undefined}:x)})),
 batchMarkPrepared:ids=>setData(d=>{const selected=new Set(ids),now=new Date().toISOString();return {...d,items:d.items.map(x=>selected.has(x.id)?{...x,preparationStatus:'prepared',updatedAt:now}:x)}}),
 batchUpdateItems:(ids,patch)=>setData(d=>{const selected=new Set(ids),now=new Date().toISOString();return {...d,items:d.items.map(x=>selected.has(x.id)?applyBatchItemPatch(x,patch,now):x)}}),
 batchRemoveItems:ids=>setData(d=>{const selected=new Set(ids);return {...d,items:d.items.map(x=>selected.has(x.id)&&x.isSystemItem?{...x,hidden:true,visibilityOverride:'hide' as const}:x).filter(x=>!selected.has(x.id)||x.isSystemItem)}}),
 batchCategories:(ids,action)=>setData(d=>{const selected=new Set(ids),hidden=action==='hide',override=hidden?'hide' as const:'show' as const;const forced=hidden?[]:[...d.categories.filter(c=>c.visibilityOverride==='show').map(c=>c.id),...ids];const base=d.items.map(i=>selected.has(i.categoryId)&&i.visibilityOverride!=='hide'?{...i,hidden}:i);const items=hidden?base:generateChecklist(d.profile,base,forced);return {...d,categories:d.categories.map(c=>selected.has(c.id)?{...c,hidden,visibilityOverride:override}:c),items}}),
 batchRemoveCategories:(ids,itemAction)=>setData(d=>{const selected=new Set(ids),customIds=new Set(d.categories.filter(c=>selected.has(c.id)&&!c.isSystemCategory&&c.id!=='uncategorized').map(c=>c.id));const categories=d.categories.filter(c=>!customIds.has(c.id)).map(c=>selected.has(c.id)&&c.isSystemCategory?{...c,hidden:true,visibilityOverride:'hide' as const}:c);const items=itemAction==='delete'?d.items.filter(i=>!customIds.has(i.categoryId)):d.items.map(i=>customIds.has(i.categoryId)?{...i,categoryId:'uncategorized'}:i);return {...d,categories:categories.map(c=>c.id==='uncategorized'&&items.some(i=>i.categoryId==='uncategorized')?{...c,hidden:false}:c),items}}),
 reset:()=>setData(d=>{const base=createDefaultData();const items=generateChecklist(d.profile);return {...base,version:DATA_VERSION,onboarded:true,profile:d.profile,items,categories:generateCategories(d.profile,items)}}),clear:()=>setData(createDefaultData()),replace:d=>setData(migrateData(d))}),[data,ready])
 return <Context.Provider value={value}>{children}</Context.Provider>
}
export const useChecklist=()=>{const value=useContext(Context);if(!value)throw new Error('Provider missing');return value}
