'use client'
import { PointerEvent as ReactPointerEvent,useMemo,useRef,useState } from 'react'
import { ArrowLeft,Check,Eye,EyeOff,GripVertical,Plus,Pencil,Trash2 } from 'lucide-react'
import Link from 'next/link'
import { AppShell } from '@/components/AppShell'
import { Modal } from '@/components/ui/Modal'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { DynamicIcon } from '@/components/ui/Icons'
import { useChecklist } from '@/hooks/useChecklist'
import { Category } from '@/types/checklist'
import { uid } from '@/lib/utils'
import { useToast } from '@/components/ui/Toast'

const icons=['Folder','Star','BookOpen','Heart','Plane','Music','Dumbbell','Coffee']
type CatFilter='all'|'visible'|'hidden'|'custom'

export default function Categories(){
 const {data,addCategory,updateCategory,reorderCategories,batchCategories,batchRemoveCategories}=useChecklist();const toast=useToast();const [editing,setEditing]=useState<Category>();const [name,setName]=useState('');const [icon,setIcon]=useState('Folder');const [open,setOpen]=useState(false);const [manage,setManage]=useState(false);const [filter,setFilter]=useState<CatFilter>('all');const [selected,setSelected]=useState<Set<string>>(new Set());const [removeOpen,setRemoveOpen]=useState(false);const [itemAction,setItemAction]=useState<'move'|'delete'>('move');const [dragging,setDragging]=useState<string>();const draggingRef=useRef<string|undefined>(undefined)
 const ordered=useMemo(()=>[...data.categories].sort((a,b)=>a.order-b.order),[data.categories]);const filtered=useMemo(()=>ordered.filter(c=>filter==='visible'?!c.hidden:filter==='hidden'?c.hidden:filter==='custom'?!c.isSystemCategory:true),[ordered,filter]);const allSelected=filtered.length>0&&filtered.every(c=>selected.has(c.id));const selectedCustom=data.categories.filter(c=>selected.has(c.id)&&!c.isSystemCategory&&c.id!=='uncategorized');const affected=data.items.filter(i=>selectedCustom.some(c=>c.id===i.categoryId)).length
 const show=(c?:Category)=>{setEditing(c);setName(c?.name||'');setIcon(c?.icon||'Folder');setOpen(true)}
 const save=()=>{if(!name.trim())return;const c=editing?{...editing,name:name.trim(),icon}:{id:uid(),name:name.trim(),icon,order:Math.max(-1,...data.categories.map(category=>category.order))+1,isSystemCategory:false};editing?updateCategory(c):addCategory(c);toast(editing?'分类已保存':'分类已添加');setOpen(false)}
 const toggle=(id:string)=>setSelected(s=>{const next=new Set(s);next.has(id)?next.delete(id):next.add(id);return next})
 const finishManage=()=>{setManage(false);setSelected(new Set());setDragging(undefined);draggingRef.current=undefined}
 const applyVisibility=(action:'show'|'hide')=>{if(!selected.size)return;batchCategories([...selected],action);toast(action==='show'?'所选分类已显示':'所选分类已隐藏');finishManage()}
 const moveCategory=(from:string,to:string)=>{if(from===to)return;const visibleIds=filtered.map(c=>c.id);const fromIndex=visibleIds.indexOf(from);const toIndex=visibleIds.indexOf(to);if(fromIndex<0||toIndex<0)return;visibleIds.splice(toIndex,0,...visibleIds.splice(fromIndex,1));const visibleSet=new Set(visibleIds);let index=0;const allIds=ordered.map(c=>visibleSet.has(c.id)?visibleIds[index++]:c.id);reorderCategories(allIds)}
 const startDrag=(event:ReactPointerEvent<HTMLButtonElement>,id:string)=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);draggingRef.current=id;setDragging(id)}
 const drag=(event:ReactPointerEvent<HTMLButtonElement>)=>{const from=draggingRef.current;if(!from)return;const row=(document.elementFromPoint(event.clientX,event.clientY) as HTMLElement|null)?.closest<HTMLElement>('[data-category-id]');const to=row?.dataset.categoryId;if(to)moveCategory(from,to)}
 const stopDrag=(event:ReactPointerEvent<HTMLButtonElement>)=>{if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);draggingRef.current=undefined;setDragging(undefined)}
 return <AppShell hideTabs={manage}><div className="categories-sticky"><header className="page-header inline"><div className="with-back"><Link href="/" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">清单设置</p><h1>分类管理</h1></div></div><div className="header-actions">{manage?<button className="secondary compact" onClick={finishManage}>完成</button>:<><button className="secondary compact" onClick={()=>setManage(true)}>批量管理</button><button className="primary compact" onClick={()=>show()}><Plus/>新建</button></>}</div></header>
 <div className="filter-row category-filters">{([['all','全部'],['visible','显示中'],['hidden','已隐藏'],['custom','自建']] as [CatFilter,string][]).map(([value,label])=><button className={filter===value?'active':''} key={value} onClick={()=>{setFilter(value);setSelected(new Set())}}>{label}</button>)}</div></div>
 <div className="category-manager">{filtered.map(c=><div className={`${c.hidden?'hidden-category':''} ${manage?'selecting':''} ${dragging===c.id?'dragging':''}`} data-category-id={c.id} key={c.id}>{manage?<button className={`category-select ${selected.has(c.id)?'selected':''}`} aria-label={`选择${c.name}`} onClick={()=>toggle(c.id)}>{selected.has(c.id)&&<Check/>}</button>:<DynamicIcon name={c.icon}/>}<span onClick={manage?()=>toggle(c.id):undefined}><strong>{c.name}</strong><small>{c.isSystemCategory?'系统分类':'自建分类'} · {data.items.filter(i=>i.categoryId===c.id).length} 项</small></span>{manage?<button className="drag-handle" aria-label={`拖动${c.name}`} onPointerDown={event=>startDrag(event,c.id)} onPointerMove={drag} onPointerUp={stopDrag} onPointerCancel={stopDrag}><GripVertical/></button>:<><button className="icon-btn" onClick={()=>{updateCategory({...c,hidden:!c.hidden});toast(c.hidden?'分类已恢复':'分类已隐藏')}}>{c.hidden?<Eye/>:<EyeOff/>}</button>{c.id!=='uncategorized'&&<button className="icon-btn" onClick={()=>show(c)}><Pencil/></button>}</>}</div>)}</div>
 {manage&&<div className="bulk-bar"><button onClick={()=>setSelected(allSelected?new Set():new Set(filtered.map(c=>c.id)))}>{allSelected?'取消全选':'全选当前'}</button><span>已选 {selected.size} 个</span><button disabled={!selected.size} onClick={()=>applyVisibility('show')}><Eye/>显示</button><button disabled={!selected.size} onClick={()=>applyVisibility('hide')}><EyeOff/>隐藏</button><button className="danger" disabled={!selected.size} onClick={()=>setRemoveOpen(true)}><Trash2/>删除</button></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'编辑分类':'新建分类'}><label className="field"><span>分类名称 *</span><input value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="例如：社团活动"/></label><div className="icon-picker">{icons.map(value=><button key={value} className={icon===value?'selected':''} onClick={()=>setIcon(value)}><DynamicIcon name={value}/></button>)}</div><div className="actions"><button className="secondary" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={!name.trim()} onClick={save}>保存</button></div></Modal>
 <Modal open={removeOpen&&selectedCustom.length>0} onClose={()=>setRemoveOpen(false)} title="处理所选分类"><p className="lead">所选自建分类中有 {affected} 个事项。系统分类不会永久删除，只会隐藏。</p><div className="choice-list"><label><input type="radio" checked={itemAction==='move'} onChange={()=>setItemAction('move')}/><span><strong>移动到“未分类”</strong><small>保留事项，稍后可以重新整理</small></span></label><label><input type="radio" checked={itemAction==='delete'} onChange={()=>setItemAction('delete')}/><span><strong>同时删除这些事项</strong><small>自建事项删除后无法恢复</small></span></label></div><div className="actions"><button className="secondary" onClick={()=>setRemoveOpen(false)}>取消</button><button className="danger-button" onClick={()=>{batchRemoveCategories([...selected],itemAction);setRemoveOpen(false);toast('所选分类已处理');finishManage()}}>确认处理</button></div></Modal>
 <ConfirmDialog open={removeOpen&&selectedCustom.length===0} title="隐藏所选系统分类？" description="系统分类不会永久删除，之后可在“已隐藏”中重新显示。" onCancel={()=>setRemoveOpen(false)} onConfirm={()=>{batchRemoveCategories([...selected],'move');setRemoveOpen(false);toast('所选系统分类已隐藏');finishManage()}}/></AppShell>
}
