'use client'
import { useMemo,useState } from 'react';import { ArrowLeft,Check,Eye,EyeOff,Plus,Pencil,Trash2 } from 'lucide-react';import Link from 'next/link';import { AppShell } from '@/components/AppShell';import { Modal } from '@/components/ui/Modal';import { ConfirmDialog } from '@/components/ui/ConfirmDialog';import { DynamicIcon } from '@/components/ui/Icons';import { useChecklist } from '@/hooks/useChecklist';import { Category } from '@/types/checklist';import { uid } from '@/lib/utils';import { useToast } from '@/components/ui/Toast'
const icons=['Folder','Star','BookOpen','Heart','Plane','Music','Dumbbell','Coffee'];type CatFilter='all'|'visible'|'hidden'|'custom'
export default function Categories(){
 const {data,addCategory,updateCategory,batchCategories,batchRemoveCategories}=useChecklist();const toast=useToast();const [editing,setEditing]=useState<Category>();const [name,setName]=useState('');const [icon,setIcon]=useState('Folder');const [open,setOpen]=useState(false);const [manage,setManage]=useState(false);const [filter,setFilter]=useState<CatFilter>('all');const [selected,setSelected]=useState<Set<string>>(new Set());const [removeOpen,setRemoveOpen]=useState(false);const [itemAction,setItemAction]=useState<'move'|'delete'>('move')
 const filtered=useMemo(()=>data.categories.filter(c=>filter==='visible'?!c.hidden:filter==='hidden'?c.hidden:filter==='custom'?!c.isSystemCategory:true),[data.categories,filter]);const allSelected=filtered.length>0&&filtered.every(c=>selected.has(c.id));const selectedCustom=data.categories.filter(c=>selected.has(c.id)&&!c.isSystemCategory&&c.id!=='uncategorized');const affected=data.items.filter(i=>selectedCustom.some(c=>c.id===i.categoryId)).length
 const show=(c?:Category)=>{setEditing(c);setName(c?.name||'');setIcon(c?.icon||'Folder');setOpen(true)};const save=()=>{if(!name.trim())return;const c=editing?{...editing,name:name.trim(),icon}:{id:uid(),name:name.trim(),icon,order:data.categories.length,isSystemCategory:false};editing?updateCategory(c):addCategory(c);toast(editing?'分类已保存':'分类已添加');setOpen(false)};const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});const end=()=>{setManage(false);setSelected(new Set())}
 return <AppShell hideTabs={manage}><header className="page-header inline"><div className="with-back"><Link href="/" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">清单设置</p><h1>分类管理</h1></div></div><div className="header-actions">{manage?<button className="secondary compact" onClick={end}>完成</button>:<><button className="secondary compact" onClick={()=>setManage(true)}>批量管理</button><button className="primary compact" onClick={()=>show()}><Plus/>新建</button></>}</div></header>
 <div className="filter-row category-filters">{([['all','全部'],['visible','显示中'],['hidden','已隐藏'],['custom','自建']] as [CatFilter,string][]).map(([v,n])=><button className={filter===v?'active':''} key={v} onClick={()=>{setFilter(v);setSelected(new Set())}}>{n}</button>)}</div>
 <div className="category-manager">{filtered.map(c=><div className={`${c.hidden?'hidden-category':''} ${manage?'selecting':''}`} key={c.id}>{manage?<button className={`category-select ${selected.has(c.id)?'selected':''}`} onClick={()=>toggle(c.id)}>{selected.has(c.id)&&<Check/>}</button>:<DynamicIcon name={c.icon}/>}<span onClick={manage?()=>toggle(c.id):undefined}><strong>{c.name}</strong><small>{c.isSystemCategory?'系统分类':'自建分类'} · {data.items.filter(i=>i.categoryId===c.id).length} 项</small></span>{!manage&&<><button className="icon-btn" onClick={()=>{updateCategory({...c,hidden:!c.hidden});toast(c.hidden?'分类已恢复':'分类已隐藏')}}>{c.hidden?<Eye/>:<EyeOff/>}</button>{c.id!=='uncategorized'&&<button className="icon-btn" onClick={()=>show(c)}><Pencil/></button>}</>}</div>)}</div>
 {manage&&<div className="bulk-bar"><button onClick={()=>setSelected(allSelected?new Set():new Set(filtered.map(c=>c.id)))}>{allSelected?'取消全选':'全选当前'}</button><span>已选 {selected.size} 个</span><button disabled={!selected.size} onClick={()=>{batchCategories([...selected],'show');toast('所选分类已显示')}}><Eye/>显示</button><button disabled={!selected.size} onClick={()=>{batchCategories([...selected],'hide');toast('所选分类已隐藏')}}><EyeOff/>隐藏</button><button className="danger" disabled={!selected.size} onClick={()=>setRemoveOpen(true)}><Trash2/>删除</button></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'编辑分类':'新建分类'}><label className="field"><span>分类名称 *</span><input value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="例如：社团活动"/></label><div className="icon-picker">{icons.map(i=><button key={i} className={icon===i?'selected':''} onClick={()=>setIcon(i)}><DynamicIcon name={i}/></button>)}</div><div className="actions"><button className="secondary" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={!name.trim()} onClick={save}>保存</button></div></Modal>
 <Modal open={removeOpen&&selectedCustom.length>0} onClose={()=>setRemoveOpen(false)} title="处理所选分类"><p className="lead">所选自建分类中有 {affected} 个事项。系统分类不会永久删除，只会隐藏。</p><div className="choice-list"><label><input type="radio" checked={itemAction==='move'} onChange={()=>setItemAction('move')}/><span><strong>移动到“未分类”</strong><small>保留事项，稍后可以重新整理</small></span></label><label><input type="radio" checked={itemAction==='delete'} onChange={()=>setItemAction('delete')}/><span><strong>同时删除这些事项</strong><small>自建事项删除后无法恢复</small></span></label></div><div className="actions"><button className="secondary" onClick={()=>setRemoveOpen(false)}>取消</button><button className="danger-button" onClick={()=>{batchRemoveCategories([...selected],itemAction);setSelected(new Set());setRemoveOpen(false);toast('所选分类已处理')}}>确认处理</button></div></Modal>
 <ConfirmDialog open={removeOpen&&selectedCustom.length===0} title="隐藏所选系统分类？" description="系统分类不会永久删除，之后可在“已隐藏”中重新显示。" onCancel={()=>setRemoveOpen(false)} onConfirm={()=>{batchRemoveCategories([...selected],'move');setSelected(new Set());setRemoveOpen(false);toast('所选系统分类已隐藏')}}/></AppShell>
}
