'use client'
import { useState } from 'react'
import { ArrowLeft,Eye,EyeOff,Plus,Pencil,Trash2 } from 'lucide-react'
import Link from 'next/link'
import { AppShell } from '@/components/AppShell'
import { Modal } from '@/components/ui/Modal'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { DynamicIcon } from '@/components/ui/Icons'
import { useChecklist } from '@/hooks/useChecklist'
import { Category } from '@/types/checklist'
import { uid } from '@/lib/utils'
import { useToast } from '@/components/ui/Toast'
const icons=['Folder','Star','BookOpen','Heart','Plane','Music','Dumbbell','Coffee']
export default function Categories(){const {data,addCategory,updateCategory,removeCategory}=useChecklist();const [editing,setEditing]=useState<Category>();const [name,setName]=useState('');const [icon,setIcon]=useState('Folder');const [open,setOpen]=useState(false);const [deleting,setDeleting]=useState<Category>();const toast=useToast();const show=(c?:Category)=>{setEditing(c);setName(c?.name||'');setIcon(c?.icon||'Folder');setOpen(true)};const save=()=>{if(!name.trim())return;const c=editing?{...editing,name:name.trim(),icon}:{id:uid(),name:name.trim(),icon,order:data.categories.length,isSystemCategory:false};editing?updateCategory(c):addCategory(c);toast(editing?'分类已保存':'分类已添加');setOpen(false)};return <AppShell><header className="page-header inline"><div className="with-back"><Link href="/" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">清单设置</p><h1>分类管理</h1></div></div><button className="primary compact" onClick={()=>show()}><Plus/>新建</button></header><div className="category-manager">{data.categories.map(c=><div className={c.hidden?'hidden-category':''} key={c.id}><DynamicIcon name={c.icon}/><span><strong>{c.name}</strong><small>{c.isSystemCategory?'系统分类':'自建分类'}</small></span><button className="icon-btn" onClick={()=>{updateCategory({...c,hidden:!c.hidden});toast(c.hidden?'分类已恢复':'分类已隐藏')}}>{c.hidden?<Eye/>:<EyeOff/>}</button><button className="icon-btn" onClick={()=>show(c)}><Pencil/></button>{!c.isSystemCategory&&<button className="icon-btn danger-icon" onClick={()=>setDeleting(c)}><Trash2/></button>}</div>)}</div><Modal open={open} onClose={()=>setOpen(false)} title={editing?'编辑分类':'新建分类'}><label className="field"><span>分类名称 *</span><input value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="例如：社团活动"/></label><div className="icon-picker">{icons.map(i=><button key={i} className={icon===i?'selected':''} onClick={()=>setIcon(i)}><DynamicIcon name={i}/></button>)}</div><div className="actions"><button className="secondary" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={!name.trim()} onClick={save}>保存</button></div></Modal><ConfirmDialog open={!!deleting} title="删除这个分类？" description="分类下的事项也会一起删除，且无法恢复。" onCancel={()=>setDeleting(undefined)} onConfirm={()=>{if(deleting)removeCategory(deleting.id);toast('分类已删除');setDeleting(undefined)}}/></AppShell>}
