'use client'
import { ArrowLeft,Plus,ShoppingBag } from 'lucide-react'
import Link from 'next/link'
import { AppShell } from '@/components/AppShell'
import { useChecklist } from '@/hooks/useChecklist'
import { useToast } from '@/components/ui/Toast'
import { resolveRationalPrepContent } from '@/lib/rationalPrep'
export default function Later(){const {data,addItem}=useChecklist();const toast=useToast();const content=resolveRationalPrepContent(data.profile);if(!content.show)return <AppShell><header className="page-header"><div className="with-back"><Link href="/" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1></div></div><p className="lead">{content.lead}</p></header></AppShell>;return <AppShell><header className="page-header"><div className="with-back"><Link href="/" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1></div></div><p className="lead">{content.lead}</p></header><div className="suggestion-list">{content.suggestions.map(suggestion=>{const exists=data.items.some(x=>x.name===suggestion.name&&!x.hidden);return <article key={suggestion.name}><ShoppingBag/><div><h2>{suggestion.name}</h2><p>{suggestion.reason}</p></div><button disabled={exists} onClick={()=>{addItem({id:`later-${Date.now()}`,name:suggestion.name,categoryId:suggestion.categoryId,itemType:suggestion.itemType,priority:'optional',preparationStatus:suggestion.preparationStatus,purchaseStatus:suggestion.purchaseStatus,purchaseStatusOverride:suggestion.purchaseStatus,quantity:1,tags:[suggestion.tag],note:suggestion.reason,isSystemItem:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});toast('已加入清单')}}>{exists?<span>已加入</span>:<><Plus/>加入</>}</button></article>})}</div></AppShell>}

