export type Priority='essential'|'recommended'|'optional'
export type ItemType='physical'|'document'|'task'
export type PreparationStatus='unprepared'|'in_progress'|'prepared'
export type PurchaseStatus='not_required'|'to_buy'|'purchased'|'buy_after_arrival'
export type StudentStatus='new'|'returning'
export type EducationStage='secondary'|'undergraduate'|'postgraduate'
export type Gender='female'|'male'
export type AccommodationType='dorm'|'commute'
export interface ItemApplicability{studentStatuses?:StudentStatus[];educationStages?:EducationStage[];genders?:Gender[];accommodations?:AccommodationType[];militaryTraining?:boolean;outOfTown?:boolean;newStudentOnly?:boolean;returningStudentOnly?:boolean;firstDormMoveInOnly?:boolean;reason?:string}
export interface ItemRuleCondition{studentStatuses?:StudentStatus[];educationStages?:EducationStage[];accommodations?:AccommodationType[];outOfTown?:boolean;militaryTraining?:Array<'yes'|'no'|'unknown'>}
export interface ItemRuleOverride{when:ItemRuleCondition;visible?:boolean;priority?:Priority;helperText?:string;preparationStatus?:PreparationStatus;tags?:string[]}
export interface ChecklistItem{id:string;name:string;categoryId:string;itemType:ItemType;priority:Priority;priorityOverride?:Priority;preparationStatus:PreparationStatus;purchaseStatus?:PurchaseStatus;purchaseStatusOverride?:PurchaseStatus;helperText?:string;systemTipHidden?:boolean;visibilityOverride?:'hide';applicability?:ItemApplicability;rules?:ItemRuleOverride[];quantity?:number;actualPrice?:number;purchasePlatform?:string;reminderDate?:string;luggageId?:string;tags:string[];note?:string;isSystemItem:boolean;hidden?:boolean;createdAt:string;updatedAt:string}
export interface Category{id:string;name:string;icon:string;order:number;isSystemCategory:boolean;hidden?:boolean;visibilityOverride?:'show'|'hide'}
export interface Luggage{id:string;name:string;icon:string;order:number}
export interface UserProfile{studentStatus:StudentStatus;educationStage?:EducationStage;gender?:Gender;accommodation:AccommodationType;outOfTown:boolean;militaryTraining?:'yes'|'no'|'unknown';registrationDate?:string;needsIdentityConfirmation?:boolean}
export interface AppData{version:number;onboarded:boolean;profile:UserProfile;categories:Category[];items:ChecklistItem[];luggage:Luggage[]}
export interface BackupPayload{appIdentifier:'open-school-checklist';backupVersion:3;exportedAt:string;data:AppData}
