import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import { createRequire } from 'node:module'
const nodeRequire=createRequire(import.meta.url);const cache=new Map();function load(file){const key=file.replaceAll('\\','/');if(cache.has(key))return cache.get(key).exports;const module={exports:{}};cache.set(key,module);const js=ts.transpileModule(fs.readFileSync(key,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const localRequire=request=>{if(request.startsWith('.')){let resolved=new URL(request,`file:///${key}`).pathname.slice(1).replaceAll('/','\\');if(!resolved.endsWith('.ts'))resolved+='.ts';return load(resolved)}return nodeRequire(request)};vm.runInNewContext(js,{module,exports:module.exports,require:localRequire,Date,console,Set,Map},{filename:key});return module.exports}
const {generateChecklist,generateCategories}=load('src/lib/checklistGenerator.ts');const base={militaryTraining:'no',enableSkincare:true,enableMakeup:true,enableBudget:true,enableLuggage:true};const scenarios=[
 ['A 本科新生·住校·异地',{...base,studentStatus:'new',educationStage:'undergraduate',accommodation:'dorm',outOfTown:true},['录取通知书','床垫','短袖','牙刷'],['本科毕业证','查看通勤路线']],
 ['B 本科新生·住校·本地',{...base,studentStatus:'new',educationStage:'undergraduate',accommodation:'dorm',outOfTown:false},['录取通知书','床垫','牙刷'],['确认车票','行李箱']],
 ['C 本科新生·走读·本地',{...base,studentStatus:'new',educationStage:'undergraduate',accommodation:'commute',outOfTown:false},['录取通知书','查看通勤路线','手机','通勤水杯'],['床垫','牙刷','洗衣液','短袖','防晒']],
 ['D 本科新生·走读·异地',{...base,studentStatus:'new',educationStage:'undergraduate',accommodation:'commute',outOfTown:true},['录取通知书','床单','牙刷','短袖','查看通勤路线'],['床帘','宿舍入住登记','确认宿舍床铺尺寸']],
 ['E 研究生新生·住校·异地',{...base,studentStatus:'new',educationStage:'postgraduate',accommodation:'dorm',outOfTown:true},['本科毕业证','本科学位证','床垫'],['团员证','查看通勤路线']],
 ['F 研究生新生·走读·本地',{...base,studentStatus:'new',educationStage:'postgraduate',accommodation:'commute',outOfTown:false},['本科毕业证','查看研究生培养系统','查看通勤路线'],['床垫','洗发水','短袖']],
 ['G 研究生新生·走读·异地',{...base,studentStatus:'new',educationStage:'postgraduate',accommodation:'commute',outOfTown:true},['本科毕业证','床单','洗发水','短袖'],['床帘','宿舍入住登记']],
 ['H 老生·住校·异地',{...base,studentStatus:'returning',educationStage:undefined,accommodation:'dorm',outOfTown:true},['学生证 / 校园卡','查看新学期课表','牙刷','洗衣液'],['录取通知书','床垫','漱口杯']],
 ['I 老生·住校·本地',{...base,studentStatus:'returning',educationStage:undefined,accommodation:'dorm',outOfTown:false},['查看新学期开学通知','牙刷','洗衣液'],['录取通知书','床垫','漱口杯','确认车票']],
 ['J 老生·走读·本地',{...base,studentStatus:'returning',educationStage:undefined,accommodation:'commute',outOfTown:false},['查看新学期课表','查看通勤路线','手机','校园卡 / 学生证'],['录取通知书','床垫','牙刷','洗衣液','短袖','创可贴']],
 ['K 老生·走读·异地',{...base,studentStatus:'returning',educationStage:undefined,accommodation:'commute',outOfTown:true},['查看新学期课表','查看通勤路线','短袖','洗衣液'],['录取通知书','床帘','宿舍入住登记']],
]
for(const [label,profile,must,mustNot] of scenarios){const all=generateChecklist(profile);const visible=all.filter(x=>!x.hidden);const names=new Set(visible.map(x=>x.name));for(const name of must)if(!names.has(name))throw new Error(`${label} 缺少：${name}`);for(const name of mustNot)if(names.has(name))throw new Error(`${label} 不应出现：${name}`);const categories=generateCategories(profile,all);for(const c of categories)if(!c.hidden&&!visible.some(i=>i.categoryId===c.id))throw new Error(`${label} 显示空分类：${c.name}`);if(profile.studentStatus==='returning'&&profile.accommodation==='dorm'){const toothbrush=visible.find(x=>x.name==='牙刷');if(toothbrush?.priority==='essential')throw new Error(`${label} 牙刷仍为必需`)}if(profile.accommodation==='commute'&&!profile.outOfTown){for(const id of ['dorm','wash','clean','clothes','beauty','food'])if(categories.find(c=>c.id===id&&!c.hidden))throw new Error(`${label} 不应显示分类：${id}`)}console.log(`${label}: ${visible.length} 项；${categories.filter(c=>!c.hidden).length} 分类；${visible.filter(x=>x.priority==='essential').length} 必需`)}
const noTraining=generateChecklist({...base,studentStatus:'new',educationStage:'undergraduate',accommodation:'dorm',outOfTown:true,militaryTraining:'no'});if(noTraining.some(x=>!x.hidden&&x.categoryId==='training'))throw new Error('不军训仍显示军训用品');console.log('场景矩阵与军训过滤通过')

