'use client'
import { Suspense,useMemo,useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { CheckCheck,Filter,Plus,Search,SlidersHorizontal,Trash2,X } from 'lucide-react'
import { AppShell } from '@/components/AppShell'
import { ChecklistRow } from '@/components/ChecklistRow'
import { ItemSheet } from '@/components/ItemSheet'
import { Modal } from '@/components/ui/Modal'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { useChecklist } from '@/hooks/useChecklist'
import { ChecklistItem,PreparationStatus,Priority,PurchaseStatus } from '@/types/checklist'
import { isDone,markPrepared,markUnprepared,progress } from '@/lib/utils'
import { getVisibleItems,matchesQuickFilter,QuickFilter } from '@/lib/selectors'
import { useToast } from '@/components/ui/Toast'
import { preparationStatusLabels,preparationStatuses,priorityLabels,purchaseStatusLabels,purchaseStatuses } from '@/lib/constants'
import { BatchItemPatch } from '@/lib/batchItems'
import { isPackedForLuggage } from '@/lib/itemTransitions'
const quicks:[QuickFilter,string][]=[['all','全部'],['unprepared','未准备'],['in_progress','准备中'],['prepared','已准备'],['essential','必需']]
function Page(){
 const params=useSearchParams();const {data,updateItem,batchMarkPrepared,batchUpdateItems,batchRemoveItems}=useChecklist();const toast=useToast();const initial=(params.get('quick')||'all') as QuickFilter
 const [query,setQuery]=useState('');const [quick,setQuick]=useState<QuickFilter>(quicks.some(([v])=>v===initial)?initial:'all');const [category,setCategory]=useState(params.get('category')||'');const [priority,setPriority]=useState<Priority|''>('');const [preparation,setPreparation]=useState<PreparationStatus|''>('');const [purchase,setPurchase]=useState<PurchaseStatus|''>('');const [location,setLocation]=useState(params.get('location')||'');const [filters,setFilters]=useState(false);const [editing,setEditing]=useState<ChecklistItem>();const [adding,setAdding]=useState(false);const [manage,setManage]=useState(false);const [selected,setSelected]=useState<Set<string>>(new Set());const [confirmDelete,setConfirmDelete]=useState(false);const [bulkSettings,setBulkSettings]=useState(false);const [bulkCategory,setBulkCategory]=useState('');const [bulkPriority,setBulkPriority]=useState<Priority|''>('');const [bulkPreparation,setBulkPreparation]=useState<PreparationStatus|''>('');const [bulkPurchase,setBulkPurchase]=useState<PurchaseStatus|''>('');const [bulkLocation,setBulkLocation]=useState('')
 const categories=data.categories.filter(c=>!c.hidden);const visible=useMemo(()=>getVisibleItems(data.items,data.categories).filter(i=>{const cat=data.categories.find(c=>c.id===i.categoryId);const text=`${i.name} ${cat?.name||''} ${i.tags.join(' ')} ${i.helperText||''} ${i.note||''}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(!category||i.categoryId===category)&&(!priority||i.priority===priority)&&(!preparation||i.preparationStatus===preparation)&&(!purchase||i.purchaseStatus===purchase)&&(!location||(location==='packed'?isPackedForLuggage(i):i.luggageId===location))&&matchesQuickFilter(i,quick)}),[data,query,quick,category,priority,preparation,purchase,location])
 const grouped=categories.map(c=>({c,items:visible.filter(i=>i.categoryId===c.id)})).filter(g=>g.items.length);const allSelected=visible.length>0&&visible.every(i=>selected.has(i.id));const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});const title=quick==='prepared'?'已准备':quick==='in_progress'?'准备中':quick==='unprepared'?'未准备':'我的清单'
 const resetBulk=()=>{setBulkCategory('');setBulkPriority('');setBulkPreparation('');setBulkPurchase('');setBulkLocation('')}
 const finishBatchEdit=()=>{setBulkSettings(false);setSelected(new Set());setManage(false);resetBulk()}
 const applyBulkSettings=()=>{const patch:BatchItemPatch={};if(bulkCategory)patch.categoryId=bulkCategory;if(bulkPriority)patch.priority=bulkPriority;if(bulkPreparation)patch.preparationStatus=bulkPreparation;if(bulkPurchase)patch.purchaseStatus=bulkPurchase;if(bulkLocation)patch.luggageId=bulkLocation==='__clear__'?null:bulkLocation;if(!Object.keys(patch).length)return;try{batchUpdateItems([...selected],patch);toast(`已更新 ${selected.size} 个事项`);finishBatchEdit()}catch{toast('批量更新失败，请重试')}}
 const endManage=finishBatchEdit
 return <AppShell hideTabs={manage}><div className="checklist-sticky"><header className="page-header inline"><div><p className="eyebrow">准备进度 · 购买情况 · 放置位置</p><h1>{title}</h1></div><div className="header-actions">{manage?<button className="secondary compact" onClick={endManage}>完成</button>:<><button className="secondary compact" onClick={()=>setManage(true)}>管理</button><button className="primary compact" onClick={()=>setAdding(true)}><Plus/>添加</button></>}</div></header>
 <div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索事项、分类、标签或备注"/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><div className="filter-row">{quicks.map(([v,n])=><button key={v} className={quick===v?'active':''} onClick={()=>{setQuick(v);setSelected(new Set())}}>{n}</button>)}<button className={category||priority||preparation||purchase||location?'active':''} onClick={()=>setFilters(true)}><Filter/>更多筛选</button></div></div>
 {manage&&<p className="manage-hint">仅选择当前筛选结果中的事项；系统事项删除后会转为隐藏。</p>}
 {grouped.length?<div className="groups">{grouped.map(({c,items})=>{const p=progress(getVisibleItems(data.items,data.categories).filter(i=>i.categoryId===c.id));return <section className="check-group" key={c.id}><header><h2>{c.name}</h2><span>{p.done} / {p.total}</span></header><div>{items.map(item=><ChecklistRow key={item.id} item={item} locationName={data.luggage.find(l=>l.id===item.luggageId)?.name} selectMode={manage} selected={selected.has(item.id)} onSelect={()=>toggle(item.id)} onOpen={()=>setEditing(item)} onToggle={()=>updateItem(isDone(item)?markUnprepared(item):markPrepared(item))}/>)}</div></section>})}</div>:<div className="empty-state"><Search/><h2>没有找到符合条件的事项</h2><p>试试更换筛选条件，或添加一个新事项。</p><button className="primary" onClick={()=>setAdding(true)}><Plus/>添加事项</button></div>}
 {manage&&<div className="bulk-bar"><button onClick={()=>setSelected(allSelected?new Set():new Set(visible.map(i=>i.id)))}>{allSelected?'取消全选':'全选当前'}</button><span>已选 {selected.size} 项</span><button disabled={!selected.size} onClick={()=>setBulkSettings(true)}><SlidersHorizontal/>设置</button><button disabled={!selected.size} onClick={()=>{batchMarkPrepared([...selected]);toast(`已将 ${selected.size} 项标记为已准备`);setSelected(new Set())}}><CheckCheck/>已准备</button><button className="danger" disabled={!selected.size} onClick={()=>setConfirmDelete(true)}><Trash2/>删除</button></div>}
 <ItemSheet open={adding} onClose={()=>setAdding(false)} initialCategory={category||categories[0]?.id}/><ItemSheet open={!!editing} onClose={()=>setEditing(undefined)} item={editing}/>
 <Modal open={filters} onClose={()=>setFilters(false)} title="筛选事项"><div className="filter-form"><label className="field"><span>分类</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分类</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>必要程度</span><select value={priority} onChange={e=>setPriority(e.target.value as Priority|'')}><option value="">全部必要程度</option>{Object.entries(priorityLabels).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="field"><span>准备状态</span><select value={preparation} onChange={e=>setPreparation(e.target.value as PreparationStatus|'')}><option value="">全部状态</option>{preparationStatuses.map(v=><option key={v} value={v}>{preparationStatusLabels[v]}</option>)}</select></label><label className="field"><span>购买情况</span><select value={purchase} onChange={e=>setPurchase(e.target.value as PurchaseStatus|'')}><option value="">全部购买情况</option>{purchaseStatuses.map(v=><option key={v} value={v}>{purchaseStatusLabels[v]}</option>)}</select></label><label className="field"><span>放置位置</span><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">全部位置</option><option value="packed">已装箱</option>{data.luggage.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><div className="actions"><button className="secondary" onClick={()=>{setCategory('');setPriority('');setPreparation('');setPurchase('');setLocation('')}}>清除</button><button className="primary" onClick={()=>setFilters(false)}>查看结果</button></div></Modal>
 <Modal open={bulkSettings} onClose={()=>{setBulkSettings(false);resetBulk()}} title={`批量设置 · ${selected.size} 项`}><p className="bulk-settings-note">只填写需要修改的字段，留空字段保持原样；所选设置会应用到全部已选事项。</p><div className="filter-form"><label className="field"><span>分类</span><select value={bulkCategory} onChange={e=>setBulkCategory(e.target.value)}><option value="">不修改</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>必要程度</span><select value={bulkPriority} onChange={e=>setBulkPriority(e.target.value as Priority|'')}><option value="">不修改</option>{Object.entries(priorityLabels).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="field"><span>准备状态</span><select value={bulkPreparation} onChange={e=>setBulkPreparation(e.target.value as PreparationStatus|'')}><option value="">不修改</option>{preparationStatuses.map(v=><option key={v} value={v}>{preparationStatusLabels[v]}</option>)}</select></label><label className="field"><span>购买情况</span><select value={bulkPurchase} onChange={e=>setBulkPurchase(e.target.value as PurchaseStatus|'')}><option value="">不修改</option>{purchaseStatuses.map(v=><option key={v} value={v}>{purchaseStatusLabels[v]}</option>)}</select><small>应用到全部已选事项。</small></label><label className="field"><span>放置位置</span><select value={bulkLocation} onChange={e=>setBulkLocation(e.target.value)}><option value="">不修改</option><option value="__clear__">清除位置</option>{data.luggage.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><small>应用到全部已选事项。</small></label></div><div className="actions"><button className="secondary" onClick={resetBulk}>清空设置</button><button className="primary" disabled={!bulkCategory&&!bulkPriority&&!bulkPreparation&&!bulkPurchase&&!bulkLocation} onClick={applyBulkSettings}>应用到所选事项</button></div></Modal>
 <ConfirmDialog open={confirmDelete} title={`处理选中的 ${selected.size} 项？`} description="系统预置事项会被隐藏，自定义事项会被永久删除。" onCancel={()=>setConfirmDelete(false)} onConfirm={()=>{const n=selected.size;batchRemoveItems([...selected]);setSelected(new Set());setConfirmDelete(false);toast(`已处理 ${n} 项`)}}/></AppShell>
}
export default function Checklist(){return <Suspense><Page/></Suspense>}
