'use client'
import { ChangeEvent,useEffect,useRef,useState } from 'react'
import Link from 'next/link'
import { Calendar,ChevronRight,Download,Eye,Info,MapPin,RefreshCcw,Trash2,Upload,Users,WalletCards } from 'lucide-react'
import { AppShell } from '@/components/AppShell'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { Modal } from '@/components/ui/Modal'
import { useChecklist } from '@/hooks/useChecklist'
import { money } from '@/lib/utils'
import { getPurchaseStats } from '@/lib/selectors'
import { UserProfile } from '@/types/checklist'
import { createBackupPayload,extractBackupData } from '@/lib/dataMigration'
import { useToast } from '@/components/ui/Toast'
const educationLabels:Record<NonNullable<UserProfile['educationStage']>,string>={secondary:'初高中',undergraduate:'专本科',postgraduate:'研究生'}
export default function Profile(){
 const {data,reset,clear,replace,saveProfile}=useChecklist();const [edit,setEdit]=useState(false);const [draft,setDraft]=useState<UserProfile>(data.profile);const [confirm,setConfirm]=useState<'reset'|'clear'|'regenerate'|'restore'>();const [pendingRestore,setPendingRestore]=useState<unknown>();const input=useRef<HTMLInputElement>(null);const toast=useToast();useEffect(()=>setDraft(data.profile),[data.profile]);const stats=getPurchaseStats(data.items,data.categories)
 const download=()=>{const blob=new Blob([JSON.stringify(createBackupPayload(data),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`开学准备备份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('备份已导出')}
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{if(!file.name.toLowerCase().endsWith('.json'))throw new Error('INVALID_BACKUP');const parsed=JSON.parse(await file.text());const backup=extractBackupData(parsed);setPendingRestore(backup);setConfirm('restore')}catch{toast('无法识别该备份文件；这里只支持恢复由本网站导出的备份文件')}e.target.value=''}
 const confirmAction=()=>{const action=confirm;if(action==='clear')clear();else if(action==='reset')reset();else if(action==='regenerate'){saveProfile(draft);setEdit(false)}else if(action==='restore'&&pendingRestore){replace(pendingRestore);setPendingRestore(undefined)}setConfirm(undefined);toast(action==='clear'?'已清空数据':action==='regenerate'?'画像与清单已更新':action==='restore'?'备份已恢复':'已恢复个性化默认清单')}
 return <AppShell><header className="page-header"><p className="eyebrow">设置与数据</p><h1>我的</h1></header>
 <section className="profile-card"><div className="section-title"><h2>我的开学信息</h2><button onClick={()=>{setDraft(data.profile);setEdit(true)}}>编辑 <ChevronRight/></button></div><div className="profile-details"><span><Users/>身份：{data.profile.studentStatus==='new'?'新生':'老生返校'}</span><span><Users/>{data.profile.studentStatus==='new'?'入学阶段':'学习阶段'}：{data.profile.educationStage?educationLabels[data.profile.educationStage]:'未设置'}</span><span><Users/>性别：{data.profile.gender==='female'?'女':data.profile.gender==='male'?'男':'未设置'}</span><span><MapPin/>住宿：{data.profile.accommodation==='dorm'?'住校':'走读'} · {data.profile.outOfTown?'异地':'本地'}</span><span><Calendar/>{data.profile.registrationDate||'未填写日期'}</span></div></section>
 <Link href="/purchases" className="purchase-card purchase-link"><div className="section-title"><div><p className="eyebrow">开学采购</p><h2>实际支出 {money(stats.actual)}</h2></div><WalletCards/></div><div className="purchase-numbers"><span><small>已购买</small><strong>{stats.purchasedCount} 件</strong></span><span><small>待购买</small><strong>{stats.pendingCount} 件</strong></span><span><small>未填支出</small><strong>{stats.missingActualCount} 件</strong></span></div></Link>
 <section className="settings"><h2>清单设置</h2><Link href="/categories"><Eye/><span>显示 / 隐藏分类</span><ChevronRight/></Link><Link href="/import"><Upload/><span>导入外部清单</span><ChevronRight/></Link><button onClick={()=>setConfirm('reset')}><RefreshCcw/><span>恢复当前画像默认清单</span><ChevronRight/></button></section>
 <section className="settings backup-settings"><h2>数据备份</h2><p className="backup-help"><strong>仅用于备份和恢复本网站的数据，不支持导入 Excel、CSV 或其他外部清单。</strong><br/>导出的备份文件可在之后重新上传，继续使用原来的清单、状态、备注等数据。</p><button onClick={download}><Download/><span>导出备份</span><ChevronRight/></button><button onClick={()=>input.current?.click()}><Upload/><span>恢复备份</span><ChevronRight/></button><input hidden ref={input} type="file" accept=".json,application/json" onChange={upload}/><button className="danger-setting" onClick={()=>setConfirm('clear')}><Trash2/><span>清空数据并重新设置</span><ChevronRight/></button></section>
 <section className="settings"><h2>关于</h2><div><Info/><span>开学准备助手 · 本地网页</span><small>v2.1.0-local</small></div></section>
 <Modal open={edit} onClose={()=>setEdit(false)} title="编辑个性化信息"><div className="filter-form"><label className="field"><span>身份</span><select value={draft.studentStatus} onChange={e=>{const studentStatus=e.target.value as UserProfile['studentStatus'];setDraft({...draft,studentStatus,educationStage:draft.educationStage||'undergraduate',militaryTraining:studentStatus==='new'?(draft.militaryTraining||'unknown'):'no'})}}><option value="new">新生</option><option value="returning">老生返校</option></select></label><label className="field"><span>{draft.studentStatus==='new'?'入学阶段':'学习阶段'}</span><select value={draft.educationStage||'undergraduate'} onChange={e=>setDraft({...draft,educationStage:e.target.value as UserProfile['educationStage']})}><option value="secondary">初高中</option><option value="undergraduate">专本科</option><option value="postgraduate">研究生</option></select></label><label className="field"><span>性别</span><select value={draft.gender||''} onChange={e=>setDraft({...draft,gender:(e.target.value||undefined) as UserProfile['gender']})}><option value="">请选择</option><option value="female">女</option><option value="male">男</option></select></label><label className="field"><span>住宿方式</span><select value={draft.accommodation} onChange={e=>setDraft({...draft,accommodation:e.target.value as UserProfile['accommodation']})}><option value="dorm">住校</option><option value="commute">走读</option></select></label><label className="field"><span>是否异地</span><select value={draft.outOfTown?'yes':'no'} onChange={e=>setDraft({...draft,outOfTown:e.target.value==='yes'})}><option value="yes">是</option><option value="no">否</option></select></label>{draft.studentStatus==='new'&&<label className="field"><span>军训</span><select value={draft.militaryTraining||'unknown'} onChange={e=>setDraft({...draft,militaryTraining:e.target.value as UserProfile['militaryTraining']})}><option value="yes">参加</option><option value="no">不参加</option><option value="unknown">不确定</option></select></label>}<label className="field"><span>{draft.studentStatus==='new'?'预计报到日期':'预计返校日期'}</span><input type="date" value={draft.registrationDate||''} onChange={e=>setDraft({...draft,registrationDate:e.target.value})}/></label></div><div className="actions"><button className="secondary" onClick={()=>setEdit(false)}>取消</button><button className="primary" disabled={!draft.gender} onClick={()=>setConfirm('regenerate')}>保存并重新生成</button></div></Modal>
 <ConfirmDialog open={!!confirm} title={confirm==='clear'?'清空全部数据？':confirm==='regenerate'?'根据新情况调整清单？':confirm==='restore'?'恢复这份备份？':'恢复默认清单？'} description={confirm==='clear'?'这会删除所有修改，并重新进入首次设置。':confirm==='regenerate'?'修改后将根据新情况调整系统推荐清单，自建事项不会被删除。':confirm==='restore'?'恢复备份后，将使用备份中的数据替换当前内容。继续吗？':'将按当前身份与住宿重新生成清单，自建事项和修改会被移除。'} onCancel={()=>{setConfirm(undefined);if(confirm==='restore')setPendingRestore(undefined)}} onConfirm={confirmAction}/></AppShell>
}
