'use client'
import { ChangeEvent,useRef,useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowLeft,ClipboardPaste,FileSpreadsheet,Trash2 } from 'lucide-react'
import * as XLSX from 'xlsx'
import { AppShell } from '@/components/AppShell'
import { useChecklist } from '@/hooks/useChecklist'
import { draftsFromNames,draftsFromTable,ExternalImportDraft,parsePastedText } from '@/lib/externalImport'
import { priorityLabels } from '@/lib/constants'
import { Priority } from '@/types/checklist'
import { uid } from '@/lib/utils'
import { useToast } from '@/components/ui/Toast'

export default function ExternalImportPage(){
 const {data,addItems}=useChecklist();const router=useRouter();const toast=useToast();const fileInput=useRef<HTMLInputElement>(null);const [text,setText]=useState('');const [drafts,setDrafts]=useState<ExternalImportDraft[]>([]);const existingNames=data.items.map(item=>item.name)
 const update=(id:string,patch:Partial<ExternalImportDraft>)=>setDrafts(current=>current.map(item=>item.id===id?{...item,...patch}:item))
 const previewText=()=>{const parsed=draftsFromNames(parsePastedText(text),data.categories,existingNames);if(!parsed.length){toast('没有识别到可导入的事项');return}setDrafts(parsed)}
 const readFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(!/\.(xlsx|csv)$/i.test(file.name))throw new Error('TYPE');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error('EMPTY');const table=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:'',raw:false});const parsed=draftsFromTable(table,data.categories,existingNames);if(!parsed.length)throw new Error('EMPTY');setDrafts(parsed)}catch{toast('无法识别该文件，请确认是有效的 XLSX 或 CSV 清单')}}
 const submit=()=>{const chosen=drafts.filter(item=>item.include&&item.name.trim());if(!chosen.length){toast('请至少保留一项再导入');return}const now=new Date().toISOString();addItems(chosen.map(item=>({id:uid(),name:item.name.trim(),categoryId:item.categoryId||'uncategorized',itemType:'physical',priority:item.priority,preparationStatus:'unprepared',note:item.note.trim()||undefined,quantity:1,tags:[],isSystemItem:false,createdAt:now,updatedAt:now})));toast(`已导入 ${chosen.length} 项`);router.push('/checklist')}
 return <AppShell><header className="page-header inline"><div className="with-back"><Link href="/profile" className="icon-btn"><ArrowLeft/></Link><div><p className="eyebrow">从其他来源整理</p><h1>导入外部清单</h1></div></div></header>
 {!drafts.length?<><section className="import-source-card"><ClipboardPaste/><div><h2>粘贴清单</h2><p>支持从备忘录、微信、Word 或网页复制。多行文本优先按行识别；单行文本可用顿号、逗号或分号分隔。</p></div><label className="field full"><span>清单内容</span><textarea rows={9} value={text} onChange={event=>setText(event.target.value)} placeholder={'身份证\n录取通知书\n充电器\n床单\n洗发水'}/></label><button className="primary" disabled={!text.trim()} onClick={previewText}>识别并预览</button></section>
 <section className="import-source-card"><FileSpreadsheet/><div><h2>Excel / CSV 文件</h2><p>支持 .xlsx 和 .csv。名称为必填列；分类、重要程度、备注可选，只有一列名称也能识别。</p></div><button className="secondary" onClick={()=>fileInput.current?.click()}>选择文件并预览</button><input hidden ref={fileInput} type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={readFile}/></section></>:<section className="import-preview"><div className="section-title"><div><p className="eyebrow">导入预览</p><h2>识别到 {drafts.length} 项</h2></div><button className="secondary compact" onClick={()=>setDrafts([])}>重新选择</button></div><p className="lead">请先检查并修改。标记“可能重复”的事项默认不导入，你仍可勾选保留。</p>
 <div className="import-preview-list">{drafts.map(item=><article className={item.include?'':'excluded'} key={item.id}><div className="import-item-top"><label className="import-include"><input type="checkbox" checked={item.include} onChange={event=>update(item.id,{include:event.target.checked})}/><span>导入</span></label>{item.duplicate&&<em>可能重复</em>}<button className="icon-btn danger-icon" aria-label={`删除${item.name}`} onClick={()=>setDrafts(current=>current.filter(entry=>entry.id!==item.id))}><Trash2/></button></div><div className="form-grid"><label className="field full"><span>名称 *</span><input value={item.name} onChange={event=>update(item.id,{name:event.target.value})}/></label><label className="field"><span>分类</span><select value={item.categoryId} onChange={event=>update(item.id,{categoryId:event.target.value})}>{data.categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label className="field"><span>重要程度</span><select value={item.priority} onChange={event=>update(item.id,{priority:event.target.value as Priority})}>{(Object.entries(priorityLabels) as [Priority,string][]).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field full"><span>备注</span><textarea rows={2} value={item.note} onChange={event=>update(item.id,{note:event.target.value})}/></label></div></article>)}</div><div className="import-actions"><span>将导入 {drafts.filter(item=>item.include&&item.name.trim()).length} 项</span><button className="primary" onClick={submit}>导入到我的清单</button></div></section>}</AppShell>
}
